services:
  - type: web
    name: voucherfinder-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_PORT
        value: 5001
      - key: YOUTUBE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

